language: node_js

node_js: "12.16.1"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - npm i -g yarn
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

script:
  - yarn build 
  - yarn test --coverage --detectOpenHandles --forceExit --ci

after_success:
  # - codecov
  - curl -s https://codecov.io/bash | bash

branches:
  only:
    - master
env:
  - CODECOV_TOKEN="3c4ce940-7853-449f-a3d2-219903217d43"
  